const Home = () => {
    return ( 
        <div className="home">
            <h1>Home</h1>
             <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati consectetur optio aut necessitatibus sint, laboriosam inventore doloremque cumque in illo quisquam, impedit mollitia pariatur ex officiis quam eligendi assumenda. Similique quis voluptates eligendi quibusdam quasi laborum. Blanditiis laboriosam eveniet laborum eaque fugit, aperiam culpa deleniti hic, assumenda nam praesentium neque quo! Debitis cupiditate excepturi voluptas. Cum error eos quae illum? Voluptatum provident nesciunt tempora eligendi corporis doloribus, consequuntur officiis ad maiores dicta at aliquam accusamus aliquid hic iste inventore incidunt delectus. Excepturi hic animi quidem incidunt autem maiores, molestias cum iure cupiditate eveniet nostrum corrupti consequatur magni ullam architecto ut iusto sed facilis est facere ratione cumque perspiciatis ea reprehenderit. Sint possimus voluptates pariatur, in cupiditate ad architecto blanditiis, saepe nemo magni enim. Cum et praesentium iusto sint, culpa error ea magni dolorum voluptas illum! Id illo expedita quo ipsa voluptate deleniti reiciendis, ipsam eaque commodi, asperiores ea beatae voluptates veritatis est debitis pariatur odio quis. Sunt, maxime! Consequatur amet laborum nesciunt facilis incidunt quisquam sunt. Ipsum in consectetur consequuntur, officia adipisci minima odit maiores fuga molestias non culpa velit at explicabo aperiam dolore, rem porro voluptatem libero vitae quasi alias ut! Eius, veniam. Deleniti in laboriosam ipsa nulla dolore quo mollitia placeat provident dignissimos? Doloremque officiis molestiae blanditiis veniam soluta numquam similique dicta rerum, unde vero quaerat temporibus doloribus dolorem modi ea repellendus exercitationem quam eveniet adipisci quis quidem dolores impedit quo voluptatem! Consectetur aut odit molestiae perspiciatis nobis dolorem ea dolor debitis obcaecati error reprehenderit sequi commodi molestias reiciendis ipsam quis quos natus maxime facilis atque officia, optio voluptatibus eveniet. Voluptatum, voluptas aliquam similique cupiditate obcaecati deleniti, earum officia sequi incidunt, atque eligendi cumque sint quas a accusamus eius numquam doloremque maxime nemo quod vel! Beatae nam unde pariatur. Corporis nostrum voluptatibus, incidunt harum maiores excepturi placeat veniam!</p>
        </div>
       
     );
}
 
export default Home;    